// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv9NaKA8guDfiBxinfx4n_IUw1P7Ob6FM',
    appId: '1:727101082238:web:51505e62adde182982a62f',
    messagingSenderId: '727101082238',
    projectId: 'newchatapp-17198',
    authDomain: 'newchatapp-17198.firebaseapp.com',
    storageBucket: 'newchatapp-17198.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfHuzRJpA58kGW68c8ACnzQW0uqHxSUfM',
    appId: '1:727101082238:android:7a09b4978880ea3a82a62f',
    messagingSenderId: '727101082238',
    projectId: 'newchatapp-17198',
    storageBucket: 'newchatapp-17198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCulePhHnls9HKN-_6mivGEskb-VCKWhCI',
    appId: '1:727101082238:ios:7f91d94bf81d33e282a62f',
    messagingSenderId: '727101082238',
    projectId: 'newchatapp-17198',
    storageBucket: 'newchatapp-17198.appspot.com',
    iosBundleId: 'com.example.newchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCulePhHnls9HKN-_6mivGEskb-VCKWhCI',
    appId: '1:727101082238:ios:7f91d94bf81d33e282a62f',
    messagingSenderId: '727101082238',
    projectId: 'newchatapp-17198',
    storageBucket: 'newchatapp-17198.appspot.com',
    iosBundleId: 'com.example.newchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv9NaKA8guDfiBxinfx4n_IUw1P7Ob6FM',
    appId: '1:727101082238:web:842c2436e38eb70982a62f',
    messagingSenderId: '727101082238',
    projectId: 'newchatapp-17198',
    authDomain: 'newchatapp-17198.firebaseapp.com',
    storageBucket: 'newchatapp-17198.appspot.com',
  );

}